services:
  - type: web
    name: rag-chatbot-backend
    env: python
    region: oregon
    plan: free
    runtime: python-3.10.14
    buildCommand: cd backend && pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false